### ISSUE TITLE
Consider adding stub_status Nginx module

### ISSUE THREAD

**Issue by otravers** [devgeniem/docker-wordpress#3]
This might come handy to troubleshoot when Nginx is acting up:
https://nginx.org/en/docs/http/ngx_http_stub_status_module.html

**Comment by onnimonni** [comment]
Thanks for mentioning. Which kind of situations did you have in mind?

I doubt that we would use this module.

It's a best practice to hide or close these kind of endpoints in production so if we included this module it's only use case would only be for development.

But we want to use almost same configs in development and production so that we don't get parity problems.

So If nginx is acting up I do following:

```
# Open shell in the container
$ docker exec -it wordpress_container sh

# Check that nginx process is running
$ ps auxef

# Check that ngnix config is working
$ nginx -t

# Check that nginx port is open
$ nc localhost:$PORT -v

# Check if nginx returns 200 OK headers
$ curl -I localhost:$PORT
```

After you have checked these you can verify that the container is working and the problem is outside maybe in firewalls, networking or port mapping.

**Comment by otravers** [comment]
You're right, I should have mentioned it under your development project, you wouldn't want this in production. Thanks for the command line tips, that's useful.

**Comment by onnimonni** [comment]
No problem. It's nice that you have found these images useful.
